---
title: "Uji t 1 Sampel"
output:
  pdf_document: 
    latex_engine: pdflatex
    keep_tex: false
  word_document: default
params:
  var: NA
  mu0: NA
  test_output: NA
  interpretation_text: NA
---

```{r setup, include=FALSE}
# Set library path
.libPaths(c("~/R/library", .libPaths()))

# Load required packages
suppressMessages({
  library(knitr)
  library(rmarkdown)
})

# Set knitr options
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

## Uji t 1 Sampel

### Informasi Uji
- **Variabel yang diuji:** `r params$var`
- **Nilai hipotesis (μ₀):** `r params$mu0`

### Hasil Uji

```{r, comment=''}
if (!is.null(params$test_output) && length(params$test_output) > 0) {
  cat(paste(params$test_output, collapse="\n"))
}
```

### Interpretasi

```{r, results='asis'}
if (!is.null(params$interpretation_text) && params$interpretation_text != "") {
  # Clean up HTML tags if present
  interp_text <- gsub("<[^>]*>", "", params$interpretation_text)
  interp_text <- gsub("&nbsp;", " ", interp_text)
  interp_text <- gsub("&lt;", "<", interp_text)
  interp_text <- gsub("&gt;", ">", interp_text)
  cat(interp_text)
}
```
